create extension if not exists "uuid-ossp";

create type public.perfil_usuario as enum ('admin', 'operacao', 'consulta');
create type public.status_pedido as enum ('rascunho', 'pendente', 'finalizado', 'cancelado');
create type public.status_atendimento as enum ('nao_iniciado', 'em_producao', 'pronto', 'entregue', 'retirado', 'cancelado');
create type public.canal_venda as enum ('balcao', 'whatsapp', 'instagram', 'ifood', 'indicacao', 'outro');

create table public.perfis (
  id_usuario uuid primary key references auth.users(id) on delete cascade,
  nome_completo text not null,
  perfil public.perfil_usuario not null default 'operacao',
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table public.categorias (
  cod_categoria bigint primary key,
  categoria text not null,
  tipo_categoria text not null default 'produto',
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table public.tipos_medida (
  tipo_medida text primary key,
  simbolo text,
  tipo_unidade text,
  criado_em timestamptz not null default now()
);

create table public.regioes (
  id_regiao bigint primary key,
  regiao text not null,
  taxa numeric(10,2),
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table public.clientes (
  id_cliente bigint primary key,
  nome_cliente text not null,
  email_cliente text,
  telefone_cliente text,
  endereco_cliente text,
  id_regiao bigint,
  regiao text,
  data_nascimento date,
  preferencias_alimentares text,
  data_inclusao timestamptz,
  entrega text,
  canal_aquisicao public.canal_venda,
  primeira_compra_em timestamptz,
  ultima_compra_em timestamptz,
  consentimento_lgpd boolean not null default false,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table public.fornecedores (
  id_fornecedor bigint primary key,
  nome_fornecedor text not null,
  telefone_fornecedor text,
  email_fornecedor text,
  observacao text,
  data_inclusao timestamptz,
  endereco_fornecedor text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table public.recursos (
  id_recurso bigint primary key,
  tipo_recurso text,
  nome_recurso text not null,
  id_categoria_recurso bigint,
  desc_categoria_rec text,
  qtd_estoque numeric(12,3),
  custo_unitario numeric(10,2),
  tipo_medida text,
  data_validade date,
  data_inclusao timestamptz,
  att_estoque_pedido text,
  estoque_minimo numeric(12,3) not null default 0,
  qtd_reposicao numeric(12,3),
  id_fornecedor_preferencial bigint,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table public.produtos (
  id_produto bigint primary key,
  nome_produto text not null,
  descricao text,
  categoria bigint,
  desc_categoria text,
  preco numeric(10,2),
  disponibilidade text,
  peso numeric(12,3),
  tipo_medida text,
  data_inclusao timestamptz,
  id_recurso bigint,
  custo_estimado numeric(10,2) not null default 0,
  margem_alvo_pct numeric(6,4),
  tempo_preparo_minutos integer,
  validade_dias integer,
  url_imagem text,
  etiquetas text[] not null default '{}',
  destaque_autoatendimento boolean not null default false,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index idx_produtos_autoatendimento on public.produtos(destaque_autoatendimento, disponibilidade);

create table public.receitas (
  id_receita_item bigint generated by default as identity primary key,
  id_receita bigint,
  id_produto bigint,
  nome_produto text,
  id_recurso bigint,
  nome_recurso text,
  qtd_ingrediente numeric(12,3),
  tipo_medida text,
  perda_pct numeric(6,4) not null default 0,
  criado_em timestamptz not null default now()
);

create table public.producoes (
  id_producao bigint primary key,
  id_produto bigint,
  nome_produto text,
  qtd_produzida numeric(12,3),
  data_producao timestamptz,
  data_validade date,
  custo_lote numeric(10,2) not null default 0,
  id_usuario_criacao uuid references public.perfis(id_usuario),
  observacao text,
  criado_em timestamptz not null default now()
);

create table public.formas_pagamento (
  id_forma_pagamento bigint primary key,
  forma_pagamento text not null,
  bandeira text,
  prazo_recebimento text,
  taxa numeric(8,6),
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table public.pedidos (
  id_pedido_linha bigint generated by default as identity primary key,
  id_pedido bigint,
  data_pedido timestamptz,
  id_cliente bigint,
  nome_cliente text,
  valor_total numeric(10,2),
  status_pedido public.status_pedido not null default 'pendente',
  id_forma_pagamento bigint,
  forma_pagamento text,
  taxa_cartao numeric(10,2),
  taxa_entrega numeric(10,2),
  taxa_embalagem numeric(10,2),
  taxa_ifood numeric(10,2),
  valor_final numeric(10,2),
  desconto numeric(10,2) not null default 0,
  custo_estimado numeric(10,2) not null default 0,
  margem_contribuicao numeric(10,2) generated always as (coalesce(valor_final, 0) - custo_estimado - coalesce(taxa_cartao, 0) - coalesce(taxa_ifood, 0)) stored,
  canal_venda public.canal_venda not null default 'whatsapp',
  status_atendimento public.status_atendimento not null default 'nao_iniciado',
  prazo_entrega_em timestamptz,
  entregue_em timestamptz,
  id_usuario_criacao uuid references public.perfis(id_usuario),
  observacao text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index idx_pedidos_id_pedido on public.pedidos(id_pedido);

create table public.itens_pedido (
  id_item_pedido bigint generated by default as identity primary key,
  id_pedido bigint,
  id_produto bigint,
  nome_produto text,
  quantidade numeric(12,3),
  preco_unitario numeric(10,2),
  preco_total numeric(10,2),
  observacao text,
  custo_unitario_estimado numeric(10,2) not null default 0,
  criado_em timestamptz not null default now()
);

create table public.compras (
  id_compra_item bigint generated by default as identity primary key,
  id_compra bigint,
  id_recurso bigint,
  nome_recurso text,
  id_fornecedor bigint,
  nome_fornecedor text,
  qtd_comprada numeric(12,3),
  data_compra date,
  custo_total numeric(10,2),
  tipo_medida text,
  numero_nota text,
  criado_em timestamptz not null default now()
);

create table public.funcionarios (
  id_funcionario bigint primary key,
  nome_funcionario text,
  cargo text,
  data_admissao date,
  salario numeric(10,2),
  cpf text,
  data_nascimento date,
  telefone text,
  email text,
  endereco text,
  numero_carteira_trabalho text,
  status text,
  observacoes text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table public.movimentacoes_estoque (
  id_movimentacao_estoque bigint generated by default as identity primary key,
  id_recurso bigint,
  tipo_movimentacao text not null check (tipo_movimentacao in ('entrada', 'saida', 'ajuste', 'producao')),
  quantidade numeric(12,3),
  custo_unitario numeric(10,2),
  tabela_origem text,
  id_origem bigint,
  ocorrido_em timestamptz not null default now(),
  id_usuario_criacao uuid references public.perfis(id_usuario),
  observacao text
);

create table public.auditoria (
  id_auditoria bigint generated by default as identity primary key,
  id_usuario uuid references public.perfis(id_usuario),
  acao text not null,
  nome_entidade text not null,
  id_entidade text,
  dados_antes jsonb,
  dados_depois jsonb,
  criado_em timestamptz not null default now()
);

create or replace function public.atualizar_atualizado_em()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

create trigger atualizar_perfis_em before update on public.perfis for each row execute function public.atualizar_atualizado_em();
create trigger atualizar_clientes_em before update on public.clientes for each row execute function public.atualizar_atualizado_em();
create trigger atualizar_fornecedores_em before update on public.fornecedores for each row execute function public.atualizar_atualizado_em();
create trigger atualizar_recursos_em before update on public.recursos for each row execute function public.atualizar_atualizado_em();
create trigger atualizar_produtos_em before update on public.produtos for each row execute function public.atualizar_atualizado_em();
create trigger atualizar_pedidos_em before update on public.pedidos for each row execute function public.atualizar_atualizado_em();
create trigger atualizar_funcionarios_em before update on public.funcionarios for each row execute function public.atualizar_atualizado_em();

create or replace view public.vw_vendas_diarias with (security_invoker = true) as
select
  date_trunc('day', data_pedido at time zone 'America/Sao_Paulo')::date as data_venda,
  count(*) filter (where status_pedido <> 'cancelado') as qtd_pedidos,
  sum(valor_final) filter (where status_pedido <> 'cancelado') as receita,
  sum(margem_contribuicao) filter (where status_pedido <> 'cancelado') as margem_contribuicao,
  avg(valor_final) filter (where status_pedido <> 'cancelado') as ticket_medio
from public.pedidos
group by 1;

create or replace view public.vw_desempenho_produtos with (security_invoker = true) as
select
  p.id_produto,
  p.nome_produto,
  p.desc_categoria,
  sum(i.quantidade) as qtd_vendida,
  sum(i.preco_total) as receita_bruta,
  sum(i.custo_unitario_estimado * coalesce(i.quantidade, 0)) as custo_estimado,
  sum(coalesce(i.preco_total, 0) - (i.custo_unitario_estimado * coalesce(i.quantidade, 0))) as margem_item
from public.itens_pedido i
join public.pedidos pe on pe.id_pedido = i.id_pedido and pe.status_pedido <> 'cancelado'
left join public.produtos p on p.id_produto = i.id_produto
group by p.id_produto, p.nome_produto, p.desc_categoria;

create or replace view public.vw_clientes_rfv with (security_invoker = true) as
select
  c.id_cliente,
  c.nome_cliente,
  max(p.data_pedido) as ultima_compra_em,
  count(p.id_pedido) filter (where p.status_pedido <> 'cancelado') as qtd_pedidos,
  sum(p.valor_final) filter (where p.status_pedido <> 'cancelado') as valor_total_cliente,
  avg(p.valor_final) filter (where p.status_pedido <> 'cancelado') as ticket_medio
from public.clientes c
left join public.pedidos p on p.id_cliente = c.id_cliente
group by c.id_cliente, c.nome_cliente;

create or replace view public.vw_issues_qualidade_dados with (security_invoker = true) as
select 'clientes_sem_contato' as regra_id, 'media' as severidade, 'clientes' as tabela, id_cliente::text as id_entidade, 'Cliente sem telefone e sem email' as problema
from public.clientes
where coalesce(telefone_cliente, '') = '' and coalesce(email_cliente, '') = ''
union all
select 'produtos_sem_custo' as regra_id, 'alta' as severidade, 'produtos' as tabela, id_produto::text as id_entidade, 'Produto sem custo estimado, margem fica incompleta' as problema
from public.produtos
where custo_estimado = 0
union all
select 'pedidos_valor_final_negativo' as regra_id, 'bloqueante' as severidade, 'pedidos' as tabela, id_pedido::text as id_entidade, 'Pedido com valor final negativo' as problema
from public.pedidos
where valor_final < 0
union all
select 'recursos_abaixo_estoque_minimo' as regra_id, 'alta' as severidade, 'recursos' as tabela, id_recurso::text as id_entidade, 'Recurso abaixo do estoque minimo' as problema
from public.recursos
where coalesce(qtd_estoque, 0) < estoque_minimo;

alter table public.perfis enable row level security;
alter table public.categorias enable row level security;
alter table public.tipos_medida enable row level security;
alter table public.regioes enable row level security;
alter table public.clientes enable row level security;
alter table public.fornecedores enable row level security;
alter table public.recursos enable row level security;
alter table public.produtos enable row level security;
alter table public.receitas enable row level security;
alter table public.producoes enable row level security;
alter table public.formas_pagamento enable row level security;
alter table public.pedidos enable row level security;
alter table public.itens_pedido enable row level security;
alter table public.compras enable row level security;
alter table public.funcionarios enable row level security;
alter table public.movimentacoes_estoque enable row level security;
alter table public.auditoria enable row level security;

create or replace function public.perfil_atual()
returns public.perfil_usuario
language sql
stable
as $$
  select perfil from public.perfis where id_usuario = auth.uid() and ativo = true
$$;

create policy "leitura_publica_categorias" on public.categorias for select to anon, authenticated using (true);
create policy "leitura_publica_tipos_medida" on public.tipos_medida for select to anon, authenticated using (true);
create policy "leitura_publica_regioes" on public.regioes for select to anon, authenticated using (true);
create policy "leitura_publica_produtos" on public.produtos for select to anon, authenticated using (true);
create policy "leitura_publica_formas_pagamento" on public.formas_pagamento for select to anon, authenticated using (true);
create policy "leitura_publica_clientes" on public.clientes for select to anon, authenticated using (true);
create policy "leitura_publica_pedidos" on public.pedidos for select to anon, authenticated using (true);
create policy "leitura_publica_itens_pedido" on public.itens_pedido for select to anon, authenticated using (true);
create policy "leitura_publica_fornecedores" on public.fornecedores for select to anon, authenticated using (true);
create policy "leitura_publica_recursos" on public.recursos for select to anon, authenticated using (true);
create policy "leitura_publica_receitas" on public.receitas for select to anon, authenticated using (true);
create policy "leitura_publica_compras" on public.compras for select to anon, authenticated using (true);

create policy "app_insere_pedidos" on public.pedidos for insert to anon, authenticated with check (true);
create policy "app_insere_itens_pedido" on public.itens_pedido for insert to anon, authenticated with check (true);
create policy "app_insere_produtos" on public.produtos for insert to anon, authenticated with check (true);
create policy "app_atualiza_produtos" on public.produtos for update to anon, authenticated using (true) with check (true);
create policy "app_remove_produtos" on public.produtos for delete to anon, authenticated using (true);
create policy "app_insere_clientes" on public.clientes for insert to anon, authenticated with check (true);
create policy "app_insere_fornecedores" on public.fornecedores for insert to anon, authenticated with check (true);
create policy "app_insere_recursos" on public.recursos for insert to anon, authenticated with check (true);
create policy "app_atualiza_recursos" on public.recursos for update to anon, authenticated using (true) with check (true);
create policy "app_insere_receitas" on public.receitas for insert to anon, authenticated with check (true);
create policy "app_insere_producoes" on public.producoes for insert to anon, authenticated with check (true);
create policy "app_insere_compras" on public.compras for insert to anon, authenticated with check (true);
create policy "operacao_atualiza_pedidos" on public.pedidos for update to authenticated using (public.perfil_atual() in ('admin', 'operacao')) with check (public.perfil_atual() in ('admin', 'operacao'));
create policy "admin_gerencia_produtos" on public.produtos for all to authenticated using (public.perfil_atual() = 'admin') with check (public.perfil_atual() = 'admin');
create policy "operacao_gerencia_clientes" on public.clientes for all to authenticated using (public.perfil_atual() in ('admin', 'operacao')) with check (public.perfil_atual() in ('admin', 'operacao'));
create policy "admin_le_auditoria" on public.auditoria for select to authenticated using (public.perfil_atual() = 'admin');
