create table if not exists public.atividades (
  id_atividade bigint generated by default as identity primary key,
  titulo text not null,
  descricao text,
  status text not null default 'a_fazer' check (status in ('backlog', 'a_fazer', 'em_andamento', 'homologacao', 'producao', 'finalizado')),
  prioridade text not null default 'media' check (prioridade in ('baixa', 'media', 'alta', 'urgente')),
  responsavel text,
  categoria text,
  data_inicio date,
  prazo date,
  data_conclusao timestamptz,
  observacao text,
  ordem_quadro integer not null default 0,
  ativo boolean not null default true,
  criado_por text,
  data_criacao timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.historico_atividades (
  id_historico bigint generated by default as identity primary key,
  id_atividade bigint not null references public.atividades(id_atividade) on delete cascade,
  campo_alterado text not null,
  valor_anterior text,
  valor_novo text,
  usuario text,
  data_alteracao timestamptz not null default now()
);

create index if not exists idx_atividades_status_prazo on public.atividades(status, prazo) where ativo = true;
create index if not exists idx_atividades_responsavel on public.atividades(responsavel) where ativo = true;
create index if not exists idx_atividades_prioridade on public.atividades(prioridade) where ativo = true;
create index if not exists idx_historico_atividades_id on public.historico_atividades(id_atividade, data_alteracao desc);

create or replace function public.registrar_historico_atividade()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'criacao', null, new.status, new.criado_por);
    return new;
  end if;

  if old.status is distinct from new.status then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'status', old.status, new.status, new.responsavel);
  end if;

  if old.prioridade is distinct from new.prioridade then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'prioridade', old.prioridade, new.prioridade, new.responsavel);
  end if;

  if old.responsavel is distinct from new.responsavel then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'responsavel', old.responsavel, new.responsavel, new.responsavel);
  end if;

  if old.prazo is distinct from new.prazo then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'prazo', old.prazo::text, new.prazo::text, new.responsavel);
  end if;

  return new;
end;
$$;

create or replace function public.atualizar_timestamp_atividade()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  if new.status = 'finalizado' and old.status is distinct from 'finalizado' then
    new.data_conclusao = now();
  elsif new.status is distinct from 'finalizado' then
    new.data_conclusao = null;
  end if;
  return new;
end;
$$;

drop trigger if exists atualizar_atividades_em on public.atividades;
create trigger atualizar_atividades_em
before update on public.atividades
for each row execute function public.atualizar_timestamp_atividade();

drop trigger if exists registrar_historico_atividade_insert on public.atividades;
create trigger registrar_historico_atividade_insert
after insert on public.atividades
for each row execute function public.registrar_historico_atividade();

drop trigger if exists registrar_historico_atividade_update on public.atividades;
create trigger registrar_historico_atividade_update
after update on public.atividades
for each row execute function public.registrar_historico_atividade();

alter table public.atividades enable row level security;
alter table public.historico_atividades enable row level security;

drop policy if exists "app_le_atividades" on public.atividades;
create policy "app_le_atividades" on public.atividades for select to anon, authenticated using (true);

drop policy if exists "app_insere_atividades" on public.atividades;
create policy "app_insere_atividades" on public.atividades for insert to anon, authenticated with check (true);

drop policy if exists "app_atualiza_atividades" on public.atividades;
create policy "app_atualiza_atividades" on public.atividades for update to anon, authenticated using (true) with check (true);

drop policy if exists "app_le_historico_atividades" on public.historico_atividades;
create policy "app_le_historico_atividades" on public.historico_atividades for select to anon, authenticated using (true);

drop policy if exists "app_insere_historico_atividades" on public.historico_atividades;
create policy "app_insere_historico_atividades" on public.historico_atividades for insert to anon, authenticated with check (true);

create or replace view public.vw_resumo_atividades as
select
  count(*) filter (where ativo and status <> 'finalizado') as atividades_abertas,
  count(*) filter (where ativo and status <> 'finalizado' and prazo < current_date) as atividades_atrasadas,
  count(*) filter (where ativo and status <> 'finalizado' and prazo = current_date) as vencem_hoje,
  count(*) filter (where ativo and status <> 'finalizado' and prazo between current_date and current_date + interval '2 day') as vencem_em_ate_2_dias,
  count(*) filter (where ativo and prioridade in ('alta', 'urgente') and status <> 'finalizado') as alta_prioridade,
  count(*) filter (where ativo and status = 'finalizado' and data_conclusao >= date_trunc('week', now())) as finalizadas_semana
from public.atividades;
