create table if not exists public.responsaveis_atividades (
  id_responsavel bigint generated by default as identity primary key,
  nome text not null,
  sobrenome text not null,
  nome_completo text generated always as (trim(nome || ' ' || sobrenome)) stored,
  ativo boolean not null default true,
  data_criacao timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint responsaveis_atividades_nome_sobrenome_chk check (length(trim(nome)) > 1 and length(trim(sobrenome)) > 1),
  constraint responsaveis_atividades_nome_unico unique (nome, sobrenome)
);

insert into public.responsaveis_atividades (nome, sobrenome)
values ('Pendente', 'Atribuicao')
on conflict (nome, sobrenome) do nothing;

alter table public.atividades
  add column if not exists id_responsavel bigint references public.responsaveis_atividades(id_responsavel),
  add column if not exists data_atribuicao timestamptz;

update public.atividades a
set
  id_responsavel = r.id_responsavel,
  responsavel = r.nome_completo
from public.responsaveis_atividades r
where a.id_responsavel is null
  and r.nome = 'Pendente'
  and r.sobrenome = 'Atribuicao'
  and (a.responsavel is null or trim(a.responsavel) = '' or lower(trim(a.responsavel)) = 'pendente');

create table if not exists public.subtarefas_atividades (
  id_subtarefa bigint generated by default as identity primary key,
  id_atividade bigint not null references public.atividades(id_atividade) on delete cascade,
  titulo text not null,
  descricao text,
  status text not null default 'a_fazer' check (status in ('a_fazer', 'fazendo', 'concluida', 'impedida')),
  prioridade text not null default 'media' check (prioridade in ('baixa', 'media', 'alta', 'urgente')),
  id_responsavel bigint references public.responsaveis_atividades(id_responsavel),
  responsavel text,
  prazo date,
  data_atribuicao timestamptz,
  data_conclusao timestamptz,
  ativo boolean not null default true,
  ordem integer not null default 0,
  criado_por text,
  data_criacao timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.historico_subtarefas_atividades (
  id_historico bigint generated by default as identity primary key,
  id_subtarefa bigint not null references public.subtarefas_atividades(id_subtarefa) on delete cascade,
  campo_alterado text not null,
  valor_anterior text,
  valor_novo text,
  usuario text,
  data_alteracao timestamptz not null default now()
);

create index if not exists idx_responsaveis_atividades_ativo on public.responsaveis_atividades(ativo, nome_completo);
create index if not exists idx_atividades_id_responsavel on public.atividades(id_responsavel) where ativo = true;
create index if not exists idx_subtarefas_atividade on public.subtarefas_atividades(id_atividade, ativo, ordem);
create index if not exists idx_subtarefas_responsavel on public.subtarefas_atividades(id_responsavel) where ativo = true;
create index if not exists idx_historico_subtarefas on public.historico_subtarefas_atividades(id_subtarefa, data_alteracao desc);

create or replace function public.atualizar_timestamp_atividade()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();

  if (old.responsavel is distinct from new.responsavel or old.id_responsavel is distinct from new.id_responsavel) then
    new.data_atribuicao = now();
  end if;

  if new.status in ('finalizado', 'concluido') and old.status not in ('finalizado', 'concluido') then
    new.data_conclusao = now();
  elsif new.status not in ('finalizado', 'concluido') then
    new.data_conclusao = null;
  end if;

  return new;
end;
$$;

create or replace function public.registrar_historico_atividade()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'criacao', null, new.status, coalesce(new.responsavel, new.criado_por));
    return new;
  end if;

  if old.status is distinct from new.status then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'status', old.status, new.status, new.responsavel);
  end if;

  if old.prioridade is distinct from new.prioridade then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'prioridade', old.prioridade, new.prioridade, new.responsavel);
  end if;

  if old.responsavel is distinct from new.responsavel then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'responsavel', old.responsavel, new.responsavel, new.responsavel);
  end if;

  if old.id_responsavel is distinct from new.id_responsavel then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'id_responsavel', old.id_responsavel::text, new.id_responsavel::text, new.responsavel);
  end if;

  if old.prazo is distinct from new.prazo then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'prazo', old.prazo::text, new.prazo::text, new.responsavel);
  end if;

  if old.ativo is distinct from new.ativo then
    insert into public.historico_atividades(id_atividade, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_atividade, 'ativo', old.ativo::text, new.ativo::text, new.responsavel);
  end if;

  return new;
end;
$$;

create or replace function public.atualizar_timestamp_subtarefa()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();

  if (old.responsavel is distinct from new.responsavel or old.id_responsavel is distinct from new.id_responsavel) then
    new.data_atribuicao = now();
  end if;

  if new.status = 'concluida' and old.status is distinct from 'concluida' then
    new.data_conclusao = now();
  elsif new.status is distinct from 'concluida' then
    new.data_conclusao = null;
  end if;

  return new;
end;
$$;

create or replace function public.registrar_historico_subtarefa()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.historico_subtarefas_atividades(id_subtarefa, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_subtarefa, 'criacao', null, new.status, coalesce(new.responsavel, new.criado_por));
    return new;
  end if;

  if old.status is distinct from new.status then
    insert into public.historico_subtarefas_atividades(id_subtarefa, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_subtarefa, 'status', old.status, new.status, new.responsavel);
  end if;

  if old.prioridade is distinct from new.prioridade then
    insert into public.historico_subtarefas_atividades(id_subtarefa, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_subtarefa, 'prioridade', old.prioridade, new.prioridade, new.responsavel);
  end if;

  if old.responsavel is distinct from new.responsavel then
    insert into public.historico_subtarefas_atividades(id_subtarefa, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_subtarefa, 'responsavel', old.responsavel, new.responsavel, new.responsavel);
  end if;

  if old.prazo is distinct from new.prazo then
    insert into public.historico_subtarefas_atividades(id_subtarefa, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_subtarefa, 'prazo', old.prazo::text, new.prazo::text, new.responsavel);
  end if;

  if old.ativo is distinct from new.ativo then
    insert into public.historico_subtarefas_atividades(id_subtarefa, campo_alterado, valor_anterior, valor_novo, usuario)
    values (new.id_subtarefa, 'ativo', old.ativo::text, new.ativo::text, new.responsavel);
  end if;

  return new;
end;
$$;

drop trigger if exists atualizar_subtarefas_atividades_em on public.subtarefas_atividades;
create trigger atualizar_subtarefas_atividades_em
before update on public.subtarefas_atividades
for each row execute function public.atualizar_timestamp_subtarefa();

drop trigger if exists registrar_historico_subtarefa_insert on public.subtarefas_atividades;
create trigger registrar_historico_subtarefa_insert
after insert on public.subtarefas_atividades
for each row execute function public.registrar_historico_subtarefa();

drop trigger if exists registrar_historico_subtarefa_update on public.subtarefas_atividades;
create trigger registrar_historico_subtarefa_update
after update on public.subtarefas_atividades
for each row execute function public.registrar_historico_subtarefa();

alter table public.responsaveis_atividades enable row level security;
alter table public.subtarefas_atividades enable row level security;
alter table public.historico_subtarefas_atividades enable row level security;

drop policy if exists "app_le_responsaveis_atividades" on public.responsaveis_atividades;
create policy "app_le_responsaveis_atividades" on public.responsaveis_atividades for select to anon, authenticated using (true);

drop policy if exists "app_insere_responsaveis_atividades" on public.responsaveis_atividades;
create policy "app_insere_responsaveis_atividades" on public.responsaveis_atividades for insert to anon, authenticated with check (true);

drop policy if exists "app_atualiza_responsaveis_atividades" on public.responsaveis_atividades;
create policy "app_atualiza_responsaveis_atividades" on public.responsaveis_atividades for update to anon, authenticated using (true) with check (true);

drop policy if exists "app_le_subtarefas_atividades" on public.subtarefas_atividades;
create policy "app_le_subtarefas_atividades" on public.subtarefas_atividades for select to anon, authenticated using (true);

drop policy if exists "app_insere_subtarefas_atividades" on public.subtarefas_atividades;
create policy "app_insere_subtarefas_atividades" on public.subtarefas_atividades for insert to anon, authenticated with check (true);

drop policy if exists "app_atualiza_subtarefas_atividades" on public.subtarefas_atividades;
create policy "app_atualiza_subtarefas_atividades" on public.subtarefas_atividades for update to anon, authenticated using (true) with check (true);

drop policy if exists "app_le_historico_subtarefas_atividades" on public.historico_subtarefas_atividades;
create policy "app_le_historico_subtarefas_atividades" on public.historico_subtarefas_atividades for select to anon, authenticated using (true);
