create table if not exists public.usuarios_permitidos (
  id_usuario_permitido bigint generated by default as identity primary key,
  email text not null unique,
  nome_completo text not null,
  perfil public.perfil_usuario not null default 'operacao',
  ativo boolean not null default true,
  criado_por uuid,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

insert into public.usuarios_permitidos (email, nome_completo, perfil, ativo)
values ('restauranteversao.vegana@gmail.com', 'Administrador Versao Vegana', 'admin', true)
on conflict (email) do update
set nome_completo = excluded.nome_completo,
    perfil = excluded.perfil,
    ativo = true,
    atualizado_em = now();

create or replace function public.perfil_atual()
returns public.perfil_usuario
language sql
stable
as $$
  select perfil from public.perfis where id_usuario = auth.uid() and ativo = true
$$;

create or replace function public.usuario_elevado()
returns boolean
language sql
stable
as $$
  select coalesce(public.perfil_atual() in ('admin', 'socia'), false)
$$;

create or replace function public.registrar_perfil_usuario_autorizado()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_usuario public.usuarios_permitidos%rowtype;
begin
  select *
    into v_usuario
    from public.usuarios_permitidos
   where lower(email) = lower(new.email)
     and ativo = true;

  if not found then
    raise exception 'Email nao autorizado para acessar o sistema Versao Vegana.';
  end if;

  insert into public.perfis (id_usuario, nome_completo, perfil, ativo)
  values (new.id, v_usuario.nome_completo, v_usuario.perfil, true)
  on conflict (id_usuario) do update
  set nome_completo = excluded.nome_completo,
      perfil = excluded.perfil,
      ativo = excluded.ativo,
      atualizado_em = now();

  return new;
end;
$$;

drop trigger if exists registrar_perfil_usuario_autorizado on auth.users;
create trigger registrar_perfil_usuario_autorizado
after insert on auth.users
for each row execute function public.registrar_perfil_usuario_autorizado();

insert into public.perfis (id_usuario, nome_completo, perfil, ativo)
select u.id, p.nome_completo, p.perfil, p.ativo
  from auth.users u
  join public.usuarios_permitidos p on lower(p.email) = lower(u.email)
on conflict (id_usuario) do update
set nome_completo = excluded.nome_completo,
    perfil = excluded.perfil,
    ativo = excluded.ativo,
    atualizado_em = now();

drop trigger if exists atualizar_usuarios_permitidos_em on public.usuarios_permitidos;
create trigger atualizar_usuarios_permitidos_em
before update on public.usuarios_permitidos
for each row execute function public.atualizar_atualizado_em();

alter table public.usuarios_permitidos enable row level security;

do $$
declare
  pol record;
begin
  for pol in
    select schemaname, tablename, policyname
      from pg_policies
     where schemaname = 'public'
  loop
    execute format('drop policy if exists %I on %I.%I', pol.policyname, pol.schemaname, pol.tablename);
  end loop;
end $$;

create policy "app_le_perfis" on public.perfis for select to authenticated using (id_usuario = auth.uid() or public.usuario_elevado());
create policy "admin_atualiza_perfis" on public.perfis for update to authenticated using (public.usuario_elevado()) with check (public.usuario_elevado());
create policy "admin_le_usuarios_permitidos" on public.usuarios_permitidos for select to authenticated using (public.usuario_elevado());
create policy "admin_insere_usuarios_permitidos" on public.usuarios_permitidos for insert to authenticated with check (public.usuario_elevado());
create policy "admin_atualiza_usuarios_permitidos" on public.usuarios_permitidos for update to authenticated using (public.usuario_elevado()) with check (public.usuario_elevado());

create policy "app_le_categorias" on public.categorias for select to authenticated using (true);
create policy "app_le_tipos_medida" on public.tipos_medida for select to authenticated using (true);
create policy "app_le_regioes" on public.regioes for select to authenticated using (true);
create policy "app_le_produtos" on public.produtos for select to authenticated using (true);
create policy "app_le_formas_pagamento" on public.formas_pagamento for select to authenticated using (true);
create policy "app_le_clientes" on public.clientes for select to authenticated using (true);
create policy "app_le_pedidos" on public.pedidos for select to authenticated using (true);
create policy "app_le_itens_pedido" on public.itens_pedido for select to authenticated using (true);
create policy "app_le_fornecedores" on public.fornecedores for select to authenticated using (true);
create policy "app_le_recursos" on public.recursos for select to authenticated using (true);
create policy "app_le_receitas" on public.receitas for select to authenticated using (true);
create policy "app_le_compras" on public.compras for select to authenticated using (true);
create policy "app_le_atividades" on public.atividades for select to authenticated using (true);
create policy "app_le_responsaveis_atividades" on public.responsaveis_atividades for select to authenticated using (true);
create policy "app_le_subtarefas_atividades" on public.subtarefas_atividades for select to authenticated using (true);
create policy "app_le_historico_atividades" on public.historico_atividades for select to authenticated using (true);
create policy "app_le_historico_subtarefas_atividades" on public.historico_subtarefas_atividades for select to authenticated using (true);

create policy "app_insere_pedidos" on public.pedidos for insert to authenticated with check (true);
create policy "app_insere_itens_pedido" on public.itens_pedido for insert to authenticated with check (true);
create policy "app_insere_clientes" on public.clientes for insert to authenticated with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_atualiza_clientes" on public.clientes for update to authenticated using (public.perfil_atual() in ('admin', 'socia', 'operacao')) with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_insere_fornecedores" on public.fornecedores for insert to authenticated with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_atualiza_fornecedores" on public.fornecedores for update to authenticated using (public.perfil_atual() in ('admin', 'socia', 'operacao')) with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_insere_produtos" on public.produtos for insert to authenticated with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_atualiza_produtos" on public.produtos for update to authenticated using (public.perfil_atual() in ('admin', 'socia', 'operacao')) with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_insere_recursos" on public.recursos for insert to authenticated with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_atualiza_recursos" on public.recursos for update to authenticated using (public.perfil_atual() in ('admin', 'socia', 'operacao')) with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_insere_receitas" on public.receitas for insert to authenticated with check (public.perfil_atual() in ('admin', 'socia', 'operacao', 'cozinha'));
create policy "app_atualiza_receitas" on public.receitas for update to authenticated using (public.perfil_atual() in ('admin', 'socia', 'operacao', 'cozinha')) with check (public.perfil_atual() in ('admin', 'socia', 'operacao', 'cozinha'));
create policy "app_insere_compras" on public.compras for insert to authenticated with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_insere_producoes" on public.producoes for insert to authenticated with check (public.perfil_atual() in ('admin', 'socia', 'operacao', 'cozinha'));
create policy "app_atualiza_pedidos" on public.pedidos for update to authenticated using (public.perfil_atual() in ('admin', 'socia', 'operacao', 'cozinha')) with check (public.perfil_atual() in ('admin', 'socia', 'operacao', 'cozinha'));
create policy "app_insere_atividades" on public.atividades for insert to authenticated with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_atualiza_atividades" on public.atividades for update to authenticated using (public.perfil_atual() in ('admin', 'socia', 'operacao')) with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_insere_responsaveis_atividades" on public.responsaveis_atividades for insert to authenticated with check (public.usuario_elevado());
create policy "app_atualiza_responsaveis_atividades" on public.responsaveis_atividades for update to authenticated using (public.usuario_elevado()) with check (public.usuario_elevado());
create policy "app_insere_subtarefas_atividades" on public.subtarefas_atividades for insert to authenticated with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_atualiza_subtarefas_atividades" on public.subtarefas_atividades for update to authenticated using (public.perfil_atual() in ('admin', 'socia', 'operacao')) with check (public.perfil_atual() in ('admin', 'socia', 'operacao'));
create policy "app_insere_historico_atividades" on public.historico_atividades for insert to authenticated with check (true);
create policy "admin_le_auditoria" on public.auditoria for select to authenticated using (public.usuario_elevado());

revoke execute on function public.atualizar_status_pedido(bigint, public.status_pedido) from anon;
revoke execute on function public.atualizar_status_pedido(bigint, public.status_pedido, text) from anon;
grant execute on function public.atualizar_status_pedido(bigint, public.status_pedido) to authenticated;
grant execute on function public.atualizar_status_pedido(bigint, public.status_pedido, text) to authenticated;
